image: node:22

stages:
  - build
  - test

variables:
  PNPM_VERSION: 10.33.0

before_script:
  - npm install -g pnpm@$PNPM_VERSION
  - pnpm config set store-dir .pnpm-store
  - pnpm install

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store

build:
  stage: build
  script:
    - pnpm run build
  artifacts:
    paths:
      - apps/*/dist/
      - apps/*/.next/
      - packages/*/dist/
    expire_in: 1 week

check-types:
  stage: test
  script:
    - pnpm run check-types
